# Generated by Django 3.2.16 on 2025-11-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], max_length=10),
        ),
    ]
