# Generated by Django 3.2.16 on 2025-11-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='original_status',
            field=models.CharField(blank=True, choices=[('overdue', 'Просроченные'), ('todo', 'К выполнению'), ('in_progress', 'В работе'), ('done', 'Выполнены')], help_text='Статус до перевода в "Просрочено"', max_length=20, null=True),
        ),
    ]
