# Generated by Django 3.2.16 on 2025-11-25 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0007_task_original_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Зачада', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(verbose_name='Срок выполнения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='task',
            name='original_status',
            field=models.CharField(blank=True, choices=[('overdue', 'Просроченные'), ('todo', 'К выполнению'), ('in_progress', 'В работе'), ('done', 'Выполнены')], help_text='Статус до перевода в "Просрочено"', max_length=20, null=True, verbose_name='Статус до перевода в "Просрочено"'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], max_length=10, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('overdue', 'Просроченные'), ('todo', 'К выполнению'), ('in_progress', 'В работе'), ('done', 'Выполнены')], default='todo', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
